/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menuprojecto;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author edgarmembreno
 */
public class Cafeteria extends javax.swing.JFrame {

    /**
     * Creates new form Cafeteria
     */
    public Cafeteria() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        hamburguesa = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        apellido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cuenta = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pizza = new javax.swing.JRadioButton();
        pollo = new javax.swing.JRadioButton();
        pastel = new javax.swing.JRadioButton();
        helado = new javax.swing.JRadioButton();
        cheesecake = new javax.swing.JRadioButton();
        agua = new javax.swing.JRadioButton();
        soda = new javax.swing.JRadioButton();
        cafe = new javax.swing.JRadioButton();
        tacos = new javax.swing.JRadioButton();
        chocolate = new javax.swing.JRadioButton();
        te = new javax.swing.JRadioButton();
        pasta = new javax.swing.JRadioButton();
        galletas = new javax.swing.JRadioButton();
        bebidaenergetica = new javax.swing.JRadioButton();
        hotdog = new javax.swing.JRadioButton();
        churros = new javax.swing.JRadioButton();
        malteada = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Cuenta", "Comida", "Bebida", "Precio"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        jButton1.setText("Eliminar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Total:");

        total.setText("0");

        jButton3.setText("Cerrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(86, 86, 86)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(total, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(total)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Listar", jPanel2);

        jLabel1.setText("Nombre");

        buttonGroup1.add(hamburguesa);
        hamburguesa.setText("Hamburguesa (Lps. 20.00) ");
        hamburguesa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hamburguesaActionPerformed(evt);
            }
        });

        jLabel2.setText("Apellido");

        jLabel3.setText("Cuenta");

        jLabel4.setText("Menu Cafeteria");

        buttonGroup1.add(pizza);
        pizza.setText("Pizza (Lps. 15.00)");
        pizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pizzaActionPerformed(evt);
            }
        });

        buttonGroup1.add(pollo);
        pollo.setText("Pollo (Lps.25.00)");

        buttonGroup1.add(pastel);
        pastel.setText("Pastel (Lps. 30.00)");

        buttonGroup1.add(helado);
        helado.setText("Helado (Lps. 20.00)");

        buttonGroup1.add(cheesecake);
        cheesecake.setText("Cheesecake (Lps. 15.00)");

        buttonGroup2.add(agua);
        agua.setText("Agua (Lps. 12.00)");

        buttonGroup2.add(soda);
        soda.setText("Soda (Lps. 20.00)");

        buttonGroup2.add(cafe);
        cafe.setText("Cafe (Lps.10.00)");

        buttonGroup1.add(tacos);
        tacos.setText("Tacos (Lps. 25.00)");

        buttonGroup1.add(chocolate);
        chocolate.setText("Chocolate (Lps. 20.00)");

        buttonGroup2.add(te);
        te.setText("Té (Lps. 14.00)");

        buttonGroup1.add(pasta);
        pasta.setText("Pasta (Lps. 30.00)");

        buttonGroup1.add(galletas);
        galletas.setText("Galletas (Lps. 15.00)");

        buttonGroup2.add(bebidaenergetica);
        bebidaenergetica.setText("Bebida Energetica (Lps 25.00)");

        buttonGroup1.add(hotdog);
        hotdog.setText("Hot Dog (Lps.20.00)");

        buttonGroup1.add(churros);
        churros.setText("Churros (Lps 10.00)");

        buttonGroup2.add(malteada);
        malteada.setText("Malteada(Lps. 12.00)");

        jButton2.setText("Agregar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setText("Comida");

        jLabel7.setText("Bebida");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hamburguesa)
                            .addComponent(pizza))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(9, 9, 9)
                                    .addComponent(jLabel1)
                                    .addGap(26, 26, 26)
                                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(pollo)
                                .addComponent(tacos)
                                .addComponent(pasta)
                                .addComponent(hotdog)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(354, 354, 354)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(63, 63, 63)
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(pastel)
                                            .addComponent(helado)
                                            .addComponent(cheesecake)
                                            .addComponent(chocolate)
                                            .addComponent(galletas)
                                            .addComponent(churros))
                                        .addGap(101, 101, 101)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(agua)
                                    .addComponent(soda)
                                    .addComponent(cafe)
                                    .addComponent(te)
                                    .addComponent(malteada)
                                    .addComponent(bebidaenergetica))))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(310, 310, 310)
                .addComponent(jButton2)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(338, 338, 338))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jLabel4)
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hamburguesa)
                            .addComponent(agua))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pizza)
                            .addComponent(soda))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pollo)
                            .addComponent(cafe))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tacos)
                            .addComponent(te)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(pastel)
                        .addGap(26, 26, 26)
                        .addComponent(helado)
                        .addGap(26, 26, 26)
                        .addComponent(cheesecake)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(chocolate)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pasta)
                            .addComponent(malteada))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(galletas)
                        .addGap(10, 10, 10)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hotdog)
                    .addComponent(bebidaenergetica, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(churros))
                .addGap(39, 39, 39)
                .addComponent(jButton2)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Agregar", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 787, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (tabla.getSelectedRow() >= 0) { // valida que se elige una columna de la table
            Object numeroO = tabla.getValueAt(tabla.getSelectedRow(), 4);
            int num = (int) numeroO;
            int num2 = Integer.parseInt(total.getText());
            int tot = num2 - num;
            total.setText(Integer.toString(tot));

            lista.remove(tabla.getSelectedRow());
            DefaultTableModel x = (DefaultTableModel) tabla.getModel();
            x.removeRow(tabla.getSelectedRow());
            //tabla.setModel(x);
            JOptionPane.showMessageDialog(null, "Se elimino exitosamente");
        } else {
            JOptionPane.showMessageDialog(null, "Error! No es posible");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // menu a = new menu();
        // a.setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void hamburguesaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hamburguesaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hamburguesaActionPerformed

    private void pizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pizzaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pizzaActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try {
            String nombre1, apellido1, comida1 = "", bebida1 = "";
            int precio = 0, cuenta1;
            nombre1 = nombre.getText();
            apellido1 = apellido.getText();
            cuenta1 = Integer.parseInt(cuenta.getText());
            if (hamburguesa.isSelected()) {
                comida1 = "Hamburguesa";
                precio = 20;
            } else if (pizza.isSelected()) {
                comida1 = "Pizza";
                precio = 15;
            } else if (pollo.isSelected()) {
                comida1 = "Pollo";
                precio = 25;
            } else if (tacos.isSelected()) {
                comida1 = "Tacos";
                precio = 25;
            } else if (pasta.isSelected()) {
                comida1 = "Pasta";
                precio = 30;
            } else if (hotdog.isSelected()) {
                comida1 = "Hot dog";
                precio = 20;
            } else if (pastel.isSelected()) {
                comida1 = "Pastel";
                precio = 30;
            } else if (helado.isSelected()) {
                comida1 = "Helado";
                precio = 20;
            } else if (cheesecake.isSelected()) {
                comida1 = "Cheesecake";
                precio = 15;
            } else if (chocolate.isSelected()) {
                comida1 = "Chocolate";
                precio = 20;
            } else if (galletas.isSelected()) {
                comida1 = "Galletas";
                precio = 15;
            } else if (churros.isSelected()) {
                comida1 = "Churros";
                precio = 15;
            }
            if (agua.isSelected()) {
                bebida1 = "Hot dog";
                precio += 12;
            } else if (soda.isSelected()) {
                bebida1 = "Soda";
                precio += 20;
            } else if (cafe.isSelected()) {
                bebida1 = "Cafe";
                precio += 10;
            } else if (te.isSelected()) {
                bebida1 = "Té";
                precio += 14;
            } else if (malteada.isSelected()) {
                bebida1 = "Malteada";
                precio += 12;
            } else if (bebidaenergetica.isSelected()) {
                bebida1 = "Bebida energetica ";
                precio += 25;
            }
            int num = Integer.parseInt(total.getText());
            int tot = precio + num;
            total.setText(Integer.toString(tot));
            nombre.setText("");
            apellido.setText("");
            cuenta.setText("");
            lista.add(new arreglos_arraylist(nombre1, cuenta1, comida1, bebida1, precio, apellido1));
            Object[] nuevo = {nombre1, cuenta1, comida1, bebida1, precio};
            DefaultTableModel t = (DefaultTableModel) tabla.getModel();
            t.addRow(nuevo);
            tabla.setModel(t);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrio un error");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cafeteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cafeteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cafeteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cafeteria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cafeteria().setVisible(true);
            }
        });
    }
    ArrayList<arreglos_arraylist> lista = new ArrayList();

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton agua;
    private javax.swing.JTextField apellido;
    private javax.swing.JRadioButton bebidaenergetica;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JRadioButton cafe;
    private javax.swing.JRadioButton cheesecake;
    private javax.swing.JRadioButton chocolate;
    private javax.swing.JRadioButton churros;
    private javax.swing.JTextField cuenta;
    private javax.swing.JRadioButton galletas;
    private javax.swing.JRadioButton hamburguesa;
    private javax.swing.JRadioButton helado;
    private javax.swing.JRadioButton hotdog;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton malteada;
    private javax.swing.JTextField nombre;
    private javax.swing.JRadioButton pasta;
    private javax.swing.JRadioButton pastel;
    private javax.swing.JRadioButton pizza;
    private javax.swing.JRadioButton pollo;
    private javax.swing.JRadioButton soda;
    private javax.swing.JTable tabla;
    private javax.swing.JRadioButton tacos;
    private javax.swing.JRadioButton te;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
